# Permalinks
#
permalink:           pretty

# Setup
title:               '@hfend'
tagline:             'Designer & Software Engineer'
description:         'Hi, I am Hichem. a Designer &amp; Software Engineer from Dréan, Algeria.'
url:                 https://hfend.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              'Hichem Fendali'
  url:               https://twitter.com/_hfend
  email:             simplizine@gmail.com

# Custom vars
version:             1.0.0
