# Permalinks
#
permalink:           pretty

# Setup
title:               '@hfend'
tagline:             'Software Engineer'
description:         'Hi! My name is Hichem, Software Engineer from Algeria'
url:                 https://hfend.github.io
baseurl:             ''
#paginate:            5

# About/contact
author:
  name:              'Mohamed Hichem Fendali'
  url:               https://x.com/_hfend
  email:             simplizine@gmail.com

# Custom vars
version:             1.0.0
